name: Monthly summary

on:
  schedule:
    - cron: '23 2 1 * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Asia/Tokyo
  NOTIFY_MODE: 'newly'
  NOTIFY_FROM_TODAY: '1'
  PING_CHANNEL: '1'
  COOLDOWN_MINUTES: '180'
  BONUS_SINGLE_DELTA: '2'
  BONUS_RATIO_THRESHOLD: '0.50'
  ROBOTS_ENFORCE: '1'
  MASK_LEVEL: '1'
  ROLLOVER_HOURS_JSON: '{"Sun":2,"Mon":0,"Tue":5,"Wed":5,"Thu":5,"Fri":6,"Sat":6}'
  UA_CONTACT: 'mailto:example@example.com'

concurrency:
  group: summary-monthly
  cancel-in-progress: false

jobs:
  summary:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display trigger info
        run: echo "trigger=${{ github.event_name }} ref=${{ github.ref }} sha=${{ github.sha }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Webhook疎通テスト
        if: github.event_name == 'workflow_dispatch'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python summarize.py --period monthly --ping-only

      - name: Collect monthly dataset
        run: python watch_cheeks.py summary --days 30 --raw-output monthly_summary_raw.json

      - name: Upload raw monthly summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-summary-raw
          path: monthly_summary_raw.json
          if-no-files-found: ignore
          retention-days: 3

      - name: Generate monthly summary & notify
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python summarize.py --period monthly --raw-data monthly_summary_raw.json --history history_masked.json --output summary_masked.json

      - name: Commit masked archives
        id: commit_archives
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          retry_on: error
          retry_wait_seconds: 30
          command: |
            git config user.email "github-actions@github.com"
            git config user.name "github-actions"
            git pull --rebase --autostash origin ${{ github.ref_name }}
            git add history_masked.json summary_masked.json
            if git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
            fi
            git commit -m "chore: update monthly summary"
            git push origin HEAD:${{ github.ref_name }}

      - name: Notify commit failure
        if: ${{ failure() && steps.commit_archives.outcome == 'failure' }}
        run: echo "Monthly summary push failed; please check the workflow logs."
